%YAML:1.0
#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

Camera.type: "PinHole"

Camera.fx: 412.20587
Camera.fy: 414.17592
Camera.cx: 323.58186
Camera.cy: 223.27381

# distortion parameters
Camera.k1: 0.009337
Camera.k2: -0.075506
Camera.p1: -0.012976
Camera.p2: 0.002530
Camera.k3: 0.000000

# Camera original resolution
Camera.width: 640
Camera.height: 480

# Camera frames per second
Camera.fps: 7.0   # keep or set to your actual rate (e.g., 30.0)

# Camera.bf: 40.0  # Set based on your baseline

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# ThDepth: 40.0
# DepthMapFactor: 1.0

# Transformation from body-frame (imu) to left camera
# IMU (body) -> Camera (optical) transform
Tbc: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [ 0.9999808,  0.0033242, -0.0052331,  0.011367,
         -0.0034123,  0.9998513, -0.0168037,  0.020342,
          0.0051761,  0.0169213,  0.9998434, -0.0050164,
          0.0,        0.0,        0.0,        1.0 ]






# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 0

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 2.44e-4 #1e-3 # rad/s^0.5
IMU.NoiseAcc: 1.47e-3 #1e-2 # m/s^1.5
IMU.GyroWalk: 1e-4 # rad/s^1.5
IMU.AccWalk: 1e-3 # m/s^2.5
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 500 #1000

# ORB Extractor: Scale factor between levels in the scale pyramid 
ORBextractor.scaleFactor: 1.2 #1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8 #8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20 #20
ORBextractor.minThFAST: 7 #7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0