# ORB-SLAM3 Camera Configuration for Raspberry Pi Camera Module 3 (Standard lens) at 640x480
Camera.type: "PinHole"
Camera.fx: 658.0        # focal length in pixels (x)
Camera.fy: 658.0        # focal length in pixels (y)
Camera.cx: 320.0        # principal point x-coordinate (image center)
Camera.cy: 240.0        # principal point y-coordinate (image center)
Camera.k1: -0.28        # radial distortion coefficient k1:contentReference[oaicite:7]{index=7}
Camera.k2:  0.07        # radial distortion coefficient k2:contentReference[oaicite:8]{index=8}
Camera.p1:  0.0         # tangential distortion coefficient p1 (negligible):contentReference[oaicite:9]{index=9}
Camera.p2:  0.0         # tangential distortion coefficient p2 (negligible):contentReference[oaicite:10]{index=10}
Camera.k3:  0.0         # radial distortion coefficient k3 (assumed ~0)
Camera.width:  640      # image width in pixels
Camera.height: 480      # image height in pixels
Camera.fps: 30.0        # camera frame rate
Camera.RGB: 1           # color order: 1 for RGB (true for libcamera-ros images)

# ORB Feature Extractor Parameters (recommended defaults)
ORBextractor.nFeatures: 1000      # number of ORB features to retain
ORBextractor.scaleFactor: 1.2     # scale factor between levels in the scale pyramid
ORBextractor.nLevels: 8           # number of levels in the scale pyramid
ORBextractor.iniThFAST: 20        # FAST threshold initializer
ORBextractor.minThFAST: 7         # minimum FAST threshold

# Viewer Settings (for visualization in ORB-SLAM3)
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3

